package com.huacainfo.ace.portal.model;

import java.math.BigDecimal;
import java.util.Date;

public class Logs implements java.io.Serializable{
    /**
	 * 
	 */
	private static final long serialVersionUID = 8943020975448610386L;

	/**
	

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LOGS.ID
     *
     * @mbggenerated Mon Dec 17 16:25:17 CST 2012
     */
    private BigDecimal id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LOGS.LOG
     *
     * @mbggenerated Mon Dec 17 16:25:17 CST 2012
     */
    private String log;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LOGS.USER_ID
     *
     * @mbggenerated Mon Dec 17 16:25:17 CST 2012
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LOGS.USER_NAME
     *
     * @mbggenerated Mon Dec 17 16:25:17 CST 2012
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LOGS.CREATE_TIME
     *
     * @mbggenerated Mon Dec 17 16:25:17 CST 2012
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LOGS.TYPE
     *
     * @mbggenerated Mon Dec 17 16:25:17 CST 2012
     */
    private String objectValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LOGS.OLD
     *
     * @mbggenerated Mon Dec 17 16:25:17 CST 2012
     */
    private String old;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LOGS.NEWS
     *
     * @mbggenerated Mon Dec 17 16:25:17 CST 2012
     */
    private String news;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LOGS.NAME
     *
     * @mbggenerated Mon Dec 17 16:25:17 CST 2012
     */
    private String name;
    
    private String ip;

    private String departmentId;
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LOGS.ID
     *
     * @return the value of LOGS.ID
     *
     * @mbggenerated Mon Dec 17 16:25:17 CST 2012
     */
    public BigDecimal getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LOGS.ID
     *
     * @param id the value for LOGS.ID
     *
     * @mbggenerated Mon Dec 17 16:25:17 CST 2012
     */
    public void setId(BigDecimal id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LOGS.LOG
     *
     * @return the value of LOGS.LOG
     *
     * @mbggenerated Mon Dec 17 16:25:17 CST 2012
     */
    public String getLog() {
        return log;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LOGS.LOG
     *
     * @param log the value for LOGS.LOG
     *
     * @mbggenerated Mon Dec 17 16:25:17 CST 2012
     */
    public void setLog(String log) {
        this.log = log == null ? null : log.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LOGS.USER_ID
     *
     * @return the value of LOGS.USER_ID
     *
     * @mbggenerated Mon Dec 17 16:25:17 CST 2012
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LOGS.USER_ID
     *
     * @param userId the value for LOGS.USER_ID
     *
     * @mbggenerated Mon Dec 17 16:25:17 CST 2012
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LOGS.USER_NAME
     *
     * @return the value of LOGS.USER_NAME
     *
     * @mbggenerated Mon Dec 17 16:25:17 CST 2012
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LOGS.USER_NAME
     *
     * @param userName the value for LOGS.USER_NAME
     *
     * @mbggenerated Mon Dec 17 16:25:17 CST 2012
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LOGS.CREATE_TIME
     *
     * @return the value of LOGS.CREATE_TIME
     *
     * @mbggenerated Mon Dec 17 16:25:17 CST 2012
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LOGS.CREATE_TIME
     *
     * @param createTime the value for LOGS.CREATE_TIME
     *
     * @mbggenerated Mon Dec 17 16:25:17 CST 2012
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LOGS.TYPE
     *
     * @return the value of LOGS.TYPE
     *
     * @mbggenerated Mon Dec 17 16:25:17 CST 2012
     */
    public String getObjectValue() {
        return objectValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LOGS.TYPE
     *
     * @param type the value for LOGS.TYPE
     *
     * @mbggenerated Mon Dec 17 16:25:17 CST 2012
     */
    public void setObjectValue(String objectValue) {
        this.objectValue = objectValue == null ? null : objectValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LOGS.OLD
     *
     * @return the value of LOGS.OLD
     *
     * @mbggenerated Mon Dec 17 16:25:17 CST 2012
     */
    public String getOld() {
        return old;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LOGS.OLD
     *
     * @param old the value for LOGS.OLD
     *
     * @mbggenerated Mon Dec 17 16:25:17 CST 2012
     */
    public void setOld(String old) {
        this.old = old == null ? null : old.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LOGS.NEWS
     *
     * @return the value of LOGS.NEWS
     *
     * @mbggenerated Mon Dec 17 16:25:17 CST 2012
     */
    public String getNews() {
        return news;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LOGS.NEWS
     *
     * @param news the value for LOGS.NEWS
     *
     * @mbggenerated Mon Dec 17 16:25:17 CST 2012
     */
    public void setNews(String news) {
        this.news = news == null ? null : news.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LOGS.NAME
     *
     * @return the value of LOGS.NAME
     *
     * @mbggenerated Mon Dec 17 16:25:17 CST 2012
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LOGS.NAME
     *
     * @param name the value for LOGS.NAME
     *
     * @mbggenerated Mon Dec 17 16:25:17 CST 2012
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

	public String getIp() {
		return ip;
	}

	public void setIp(String ip) {
		this.ip = ip;
	}

	public String getDepartmentId() {
		return departmentId;
	}

	public void setDepartmentId(String departmentId) {
		this.departmentId = departmentId;
	}
    
}