package com.huacainfo.ace.portal.model;

import java.util.Date;

public class Role implements java.io.Serializable {
	/**
	 * 
	 */
	private static final long serialVersionUID = 7188152460379293997L;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ROLE.ROLE_ID
	 *
	 * @mbggenerated Fri Dec 14 11:16:28 CST 2012
	 */
	private String roleId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ROLE.ROLE_NAME
	 *
	 * @mbggenerated Fri Dec 14 11:16:28 CST 2012
	 */
	private String roleName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ROLE.CREATE_TIME
	 *
	 * @mbggenerated Fri Dec 14 11:16:28 CST 2012
	 */
	private Date createTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ROLE.CREATE_USER_ID
	 *
	 * @mbggenerated Fri Dec 14 11:16:28 CST 2012
	 */
	private String createUserId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ROLE.REMARK
	 *
	 * @mbggenerated Fri Dec 14 11:16:28 CST 2012
	 */
	private String remark;

	private String type;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ROLE.ROLE_ID
	 *
	 * @return the value of ROLE.ROLE_ID
	 *
	 * @mbggenerated Fri Dec 14 11:16:28 CST 2012
	 */
	public String getRoleId() {
		return roleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ROLE.ROLE_ID
	 *
	 * @param roleId
	 *            the value for ROLE.ROLE_ID
	 *
	 * @mbggenerated Fri Dec 14 11:16:28 CST 2012
	 */
	public void setRoleId(String roleId) {
		this.roleId = roleId == null ? null : roleId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ROLE.ROLE_NAME
	 *
	 * @return the value of ROLE.ROLE_NAME
	 *
	 * @mbggenerated Fri Dec 14 11:16:28 CST 2012
	 */
	public String getRoleName() {
		return roleName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ROLE.ROLE_NAME
	 *
	 * @param roleName
	 *            the value for ROLE.ROLE_NAME
	 *
	 * @mbggenerated Fri Dec 14 11:16:28 CST 2012
	 */
	public void setRoleName(String roleName) {
		this.roleName = roleName == null ? null : roleName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ROLE.CREATE_TIME
	 *
	 * @return the value of ROLE.CREATE_TIME
	 *
	 * @mbggenerated Fri Dec 14 11:16:28 CST 2012
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ROLE.CREATE_TIME
	 *
	 * @param createTime
	 *            the value for ROLE.CREATE_TIME
	 *
	 * @mbggenerated Fri Dec 14 11:16:28 CST 2012
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ROLE.CREATE_USER_ID
	 *
	 * @return the value of ROLE.CREATE_USER_ID
	 *
	 * @mbggenerated Fri Dec 14 11:16:28 CST 2012
	 */
	public String getCreateUserId() {
		return createUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ROLE.CREATE_USER_ID
	 *
	 * @param createUserId
	 *            the value for ROLE.CREATE_USER_ID
	 *
	 * @mbggenerated Fri Dec 14 11:16:28 CST 2012
	 */
	public void setCreateUserId(String createUserId) {
		this.createUserId = createUserId == null ? null : createUserId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ROLE.REMARK
	 *
	 * @return the value of ROLE.REMARK
	 *
	 * @mbggenerated Fri Dec 14 11:16:28 CST 2012
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ROLE.REMARK
	 *
	 * @param remark
	 *            the value for ROLE.REMARK
	 *
	 * @mbggenerated Fri Dec 14 11:16:28 CST 2012
	 */
	public void setRemark(String remark) {
		this.remark = remark == null ? null : remark.trim();
	}

	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}

	private String syid;

	public String getSyid() {
		return syid;
	}

	public void setSyid(String syid) {
		this.syid = syid;
	}

}